spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lmm-frame?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

server:
  port: 8082

lmm:


management:
  endpoints:
    web:
      exposure:
        include: "*"